# Include drupal specific configuration
- include_vars: "{{ item }}"
  with_items:
    - drupal.yml
    - version.yml
  tags:
    - configuration
    - update

- name: General | Install Application packages
  apt: "name={{ item }} state=present"
  with_items:
    - git
    - curl

- name: Drupal | Ensure MySQL is running
  command: service mysql start
  ignore_errors: yes
  tags:
    - configuration

- name: Drupal | Create Drupal database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: "{{ drupal_db_name }}"
    state: present

- name: Drupal | Create Drupal database user
  mysql_user:
    name: "{{ drupal_db_user }}"
    password: "{{ drupal_db_password }}"
    priv: "{{ drupal_db_name }}.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Drupal | Download application from Github
  sudo: false
  git:
    repo: "https://github.com/{{ application_repository }}/drupal.git"
    dest: "{{ drupal_root_path }}"
    version: "{{ application_version }}"
    accept_hostkey: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
    update: yes
    force: yes
  tags:
    - update

- name: Drupal | Current commit hash
  shell: 'git log -n 1 --pretty=format:"%H" > {{ drupal_root_path }}/.git-version'
  args:
    chdir: "{{ drupal_root_path }}"
  tags:
    - update

- name: Git | Ignore files permissions changes
  command: "git config core.filemode false chdir={{ drupal_root_path }}"
  tags:
    - update

- name: Ansible | Update scripts
  copy:
    src: "{{ drupal_root_path }}/deploy/ansible"
    dest: /etc/
  tags:
    - update

- name: Drupal | Configure Apache virtual host
  template: 
    src: etc-apache24-confd-drupal-conf
    dest: /etc/apache2/sites-available/drupal.conf
    owner: root
    mode: 755
  tags:
    - configuration

- name: Drupal | Enable Apache virtual host 
  file: src=/etc/apache2/sites-available/drupal.conf dest=/etc/apache2/sites-enabled/drupal.conf state=link
  tags:
    - configuration

- name: Apache | Restart the Apache service
  service: 
    name: apache2 
    state: restarted

- name: Drupal | Configuration file drupal-settings.php
  template: 
    src: drupal-settings.php
    dest: "{{ drupal_root_path }}/sites/default/settings.php"
    owner: www-data
    mode: 755
  tags:
    - configuration

- name: Drupal | Configuration file maestrano.json
  template: 
    src: drupal-maestrano.json
    dest: "{{ drupal_root_path }}/maestrano.json"
    owner: www-data
    group: www-data
    mode: 777
  tags:
    - configuration

- name: Drupal | Setup Drupal database
  shell: "mysql {{ drupal_db_name }} -u{{ drupal_db_user }} -p{{ drupal_db_password }} < {{ item }}"
  with_items:
    - maestrano/app/db/0_base_schema.sql
    - maestrano/app/db/1_add_mno_uid_field.sql
  args:
    chdir: "{{ drupal_root_path }}"

- name: Drupal | Set file permissions
  file:
    path: "{{ drupal_root_path }}"
    mode: 0755
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  tags:
    - configuration

- name: Drupal | Set log files permissions
  file:
    path: /var/log/apache2
    mode: 0755
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  tags:
    - configuration
