# vTiger installation
drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal
drupal_root_path: /var/lib/drupal/webapp/

# vTiger default configuration
sso_enabled: "false"
connec_enabled: "false"
maestrano_environment: "production"
server_hostname: "server_hostname"
api_key: "api_key"
api_secret: "api_secret"